_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.base import RedirectView
from django.views.generic.edit import CreateView

admin.site.site_header = 'Covoiturage JDem - Administration'

urlpatterns = [
	url('^', include('django.contrib.auth.urls')), # keeping this for the logout feature
	url(r'^auth/', include('django_auth_network_client.urls')),
	url(r'^arriere-boutique/', admin.site.urls, name='admin'),
	url(r'^covoiturage/', include('rideshare.urls')),
	url(r'^$', RedirectView.as_view(url="/covoiturage/", permanent=False)),
]

rideshare/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView

from . import views

urlpatterns = [
	url(r'^events/(?P<slug>[\x00-\x7F]+)/create-new-ride/$', views.CreateRide.as_view(), name='rideshare_ride_create'),
	url(r'^events/(?P<slug>[\x00-\x7F]+)/$', views.EventRides.as_view(), name='rideshare_ride_list'),
	url(r'^events/$', views.ListOfEvents.as_view(), name='rideshare_event_list'),
	url(r'^rides/(?P<pk>[0-9]+)/$', views.RideDetail.as_view(), name='rideshare_ride_detail'),
	url(r'^rides/(?P<pk>[0-9]+)/join/$', views.JoinRide, name='rideshare_join_ride'),
	url(r'^rides/(?P<pk>[0-9]+)/update/$', views.UpdateRide.as_view(), name = 'rideshare_ride_update'),
	url(r'^rider/new/$', views.CreateRider, name='rideshare_rider_create'),
	url(r'^rider/(?P<pk>[0-9]+)/accept/$', views.AcceptRider, name='rideshare_rider_accept'),
	url(r'^rider/(?P<pk>[0-9]+)/deny/$', views.DenyRider, name='rideshare_rider_deny'),
	url(r'^rider/(?P<pk>[0-9]+)/delete/$', views.DeleteRider, name='rideshare_rider_delete'),
	url(r'^email/$', views.SendTestEmail, name='rideshare_send_test_email'),
	url(r'^$', RedirectView.as_view(url="events/", permanent=False)),
]

rideshare/models.py
# -*- coding: utf-8 -*-
import os, datetime
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Count
from django.db.models.signals import post_save
from django.utils.text import slugify
from datetime import datetime, timedelta



class Location(models.Model):
	name = models.CharField(max_length=48)
	region = models.CharField(max_length=255, default="Île-de-France") # "Île-de-France", "Bretagne"
	locality = models.CharField(max_length=255, default="Paris") # "Paris", "Guidel"
	latitude = models.DecimalField(max_digits=8, decimal_places=6)
	longitude = models.DecimalField(max_digits=8, decimal_places=6)
	precision = models.CharField(max_length=48) # based on google maps api precision

	def __str__(self):
		#Format as :  Guidel (23.029923, 83,282193)
		return "{} — [{}, {}]".format(self.name, self.latitude, self.longitude)



class Event(models.Model):
	name = models.CharField(max_length=48, unique=True)
	slug = models.SlugField(max_length=48, unique=True)
	description = models.CharField(max_length=5000)
	location = models.ForeignKey(Location, on_delete=models.CASCADE)
	start_date = models.DateTimeField(default=datetime.now)
	end_date = models.DateTimeField(default=datetime.now)
	done = models.BooleanField(default=False)

	def __str__(self):
		return self.name



class Ride(models.Model):
	event = models.ForeignKey(Event, on_delete=models.CASCADE)
	owner = models.ForeignKey(User, related_name="owned_ride", on_delete=models.CASCADE)
	phone = models.CharField(max_length=32, default="00 00 00 00 00", verbose_name=u'Numéro de téléphone')
	riders = models.ManyToManyField(User, through="Rider", related_name="ride")
	seats = models.SmallIntegerField(default=5, verbose_name=u'Nombre total de places')
	message = models.CharField(max_length=1024, null=True, blank=True, verbose_name=u"Message pour les participants")
#	return_ride = models.ForeignKey('self', null=True, blank=True)
	is_return = models.BooleanField(default=False)
	price = models.DecimalField(max_digits=8, decimal_places=2, default=0.00, verbose_name=u'Prix par participant')
	# cost is divided equally among users

	def __str__(self):
		return '[{}] {} {}'.format(
			self.pk,
			self.owner.first_name,
			self.owner.last_name,
			)



class Stop(models.Model):
	ride = models.ForeignKey(Ride, on_delete=models.CASCADE)
	location = models.ForeignKey(Location, on_delete=models.CASCADE)
	time = models.DateTimeField()

	def __str__(self):
		return '{} — {} — {}'.format(self.ride, self.location.name, self.time)

	class Meta:
		ordering = ('time',)


class Rider(models.Model):
	ride = models.ForeignKey(Ride, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
#	joining_stop = models.ForeignKey(Stop, related_name='joining_rider') TODO : use these
#	leaving_stop = models.ForeignKey(Stop, related_name='leaving_rider')
	name = models.CharField(max_length=64, default="No Name")
	email = models.EmailField(default="no@email.com")
	phone = models.CharField(max_length=32, default="00 00 00 00 00")
	message = models.CharField(max_length=255, null=True, blank=True)
	accepted = models.BooleanField(default=False)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return '[{}] {}, riding with {}'.format(
			self.pk,
			self.name,
			self.ride.owner.first_name + '' + self.ride.owner.last_name,
			)

	def accept(self):
		self.accepted = True
		self.save()

rideshare/views.py
import random, ast
from datetime import datetime, timedelta
from django.db.models import *
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.core.mail import send_mail
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse, HttpRequest, JsonResponse
from django.shortcuts import get_object_or_404, render, render_to_response, redirect
from django.template import RequestContext
from django.utils.decorators import method_decorator
from django.utils.html import strip_tags
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView

from .models import *
from .forms import *



#	@method_decorator(login_required, name='dispatch')
class ListOfEvents(ListView):
	template_name = 'list.html'
	model = Event

	def get_context_data(self, **kwargs):
		context = super(ListOfEvents, self).get_context_data(**kwargs)
		context['url_by_slug'] = True
		context['page_title'] = "Prochains évènements"
		return context

	def dispatch(self, request, *args, **kwargs):
		if Event.objects.count() == 1 : # il n'y a qu'un évènement
			event = Event.objects.first()
			return redirect('rideshare_ride_list', event.slug)
		else:
			return super(ListOfEvents, self).dispatch(request, *args, **kwargs)



#	@method_decorator(login_required, name='dispatch')
class EventRides(ListView):
	template_name = 'rideshare/ride_list.html'
	queryset = Ride.objects.filter(stop__isnull=False).annotate(
		number_of_riders=Count('rider'),
		remaining_seats=F('seats')-Count('rider'), # counts all riders?
		departure_datetime=Min('stop__time'),
		arrival_datetime=Max('stop__time'),
		)

	def get_context_data(self, **kwargs):
		context = super(EventRides, self).get_context_data(**kwargs)
		context['event'] = Event.objects.get(slug=self.kwargs['slug']) 
		context['page_title'] = context['event'].name
		context['meta'] = context_meta() 
		return context



class RideDetail(DetailView):
	queryset = Ride.objects.filter(stop__isnull=False).annotate(
		number_of_riders=Count('rider'),
		remaining_seats=F('seats')-Count('rider'),
		departure_datetime=Min('stop__time'),
		arrival_datetime=Max('stop__time'),
		)

	def get_context_data(self, **kwargs):
		context = super(RideDetail, self).get_context_data(**kwargs)
		context['page_title'] = "Détail du trajet"
		ride = Ride.objects.get(pk=self.kwargs['pk'])
		user_riders = Rider.objects.filter(ride=ride).exclude(user=None)
		context['users_who_are_riders'] = []
		for rider in user_riders :
			context['users_who_are_riders'].append(rider.user)
		return context


class CreateRide(LoginRequiredMixin, CreateView):
	model = Ride
	fields = ['seats', 'phone', 'price']
	login_url = settings.LOGIN_URL
	redirect_field_name = 'redirect_to'

	def get_context_data(self, **kwargs):
		context = super(CreateRide, self).get_context_data(**kwargs)
		context['event'] = Event.objects.get(slug=self.kwargs['slug']) 
		context['page_title'] = "Nouveau trajet : {}".format(context['event'].name)
		return context

	def post(self, request, *args, **kwargs):

		form = request.POST

		event = get_object_or_404(Event, pk=form.get('event_id'))

		# Is this a Aller or Retour ?
		ride_type = form.get('ride_type')
		if ride_type == 'aller-retour' or ride_type == 'aller' : is_return = False
		elif ride_type == 'retour': is_return = True
		else :
			messages.error(request, "Une erreur a empêché la création de ce trajet.")
			redirect('rideshare_ride_list', slug=event.slug)

		ride = Ride(
			event = event,
			owner = request.user,
			seats = form.get('seats'),
			price = form.get('price'),
			phone = form.get('phone'),
			is_return = is_return,
			)

		ride.save()

		number_of_stops = form.get('number_of_stops')
		stop_labels = ['origin', 'destination'] # TODO : add "stop1", "stop2", ...

		for stop_label in stop_labels :

			# Register the location of this stop
			location, created = Location.objects.get_or_create(
				name = form.get(stop_label + '_place_name'),
				latitude = form.get(stop_label + '_place_latitude'),
				longitude = form.get(stop_label + '_place_longitude'),
				precision = form.get(stop_label + '_place_precision'),
				region = form.get(stop_label + '_place_region'),
				locality = form.get(stop_label + '_place_locality'),
				)

			time = (form.get(stop_label + '_date') + ' ' + form.get(stop_label + '_time')) # 22/08/2016 11:00:00
			time = datetime.strptime(time, '%d/%m/%Y %H:%M' )

			new_stop = Stop(
				ride = ride,
				location = location,
				time = time,
				)

			new_stop.save()

		if Stop.objects.filter(ride=ride):
			messages.success(request, "Félicitations, votre trajet a été créé !")
		else :
			messages.error(request, "Une erreur a empêché la création de ce trajet. Si cela se reproduit, contactez moi.")
			ride.delete()
			# TODO : cleanup this error and the one if the return radio isn't checked

		return redirect('rideshare_ride_detail', pk=ride.pk)



class UpdateRide(LoginRequiredMixin, UpdateView):
	model = Ride
	fields = ['seats', 'price', 'phone', 'message']
	template_name = 'form.html'

	def get_context_data(self, **kwargs):
		context = super(UpdateRide, self).get_context_data(**kwargs)
		context['page_title'] = "Modifier mon trajet"
		return context

	def get_success_url(self):
		return reverse('rideshare_ride_detail', kwargs={'pk':self.object.pk})


def JoinRide(request, pk):
	ride = get_object_or_404(Ride, pk=pk)
	user = request.user
	if user.is_authenticated() and user != ride.owner :
		user_pk = user.pk
	else :
		user_pk = ""
	return render(request, 'rideshare/ride_join_form.html', {'ride_pk': pk, 'user_pk': user_pk, 'page_title': 'Nouveau passager'})



#
# EMAIL PREFIX AND SUFFIX
#

def email_greeting(request):
	return  "Bonjour {},".format(request.user.get_full_name())

def email_signature(request):
	return "- L'équipe JDem"



def CreateRider(request):
	form = request.POST
	ride = get_object_or_404(Ride, pk=form.get('ride_pk'))
	if form.get('user_pk'):
		user = get_object_or_404(User, pk=form.get('user_pk'))
		name = user.get_full_name()
		email = user.email
	else :
		user = None
		name = form.get('name')
		email = form.get('email')
	phone = form.get('phone')
	message = form.get('message')
	accepted = ride.owner == user # automatically accepts the request if the user is the ride owner
	if Rider.objects.filter(ride=ride.pk, email=email).count() > 0 :
		if user and request.user == user :
			messages.info(request, 'Vous êtes déjà un des passagers ce covoiturage')
		else :
			messages.info(request, 'Ce passager participe déjà à ce covoiturage')
	elif not name or not email and not phone :
		messages.error(request, 'Il manque des informations pour ajouter ce passager.')
	else :
		if user and request.user == user or not user :
			rider = Rider(ride=ride, user=user, name=name, email=email, phone=phone, message=message, accepted=accepted)
			rider.save()
			if accepted == False : # si la demande est auto acceptée, c'est que le covoitureur a fait la demande pour lui-même
				send_mail(
					subject='Votre demande de covoiturage a été enregistrée',
					message='''
						{greeting} votre demande pour rejoindre le covoiturage {ride_url} a été enregistrée. Elle devra être validée {ride_owner}. {signature}
						'''.format(
							greeting=email_greeting(request),
							ride_url= request.build_absolute_uri(reverse('rideshare_ride_detail', args=[ride.pk,])),
							ride_owner=ride.owner.get_full_name(),
							signature=email_signature(request),
							),
					html_message='''
						<p>{greeting},</p>
						<p>Votre demande pour rejoindre le covoiturage {ride_url} a été enregistrée. Elle devra être validée {ride_owner}.</p>
						<p>{signature}</p>
						'''.format(
							greeting=email_greeting(request),
							ride_url= request.build_absolute_uri(reverse('rideshare_ride_detail', args=[ride.pk,])),
							ride_owner=ride.owner.get_full_name(),
							signature=email_signature(request),
							),
					recipient_list=[rider.email,],
					from_email=settings.DEFAULT_FROM_EMAIL,
					fail_silently=False,
				)
				messages.info(request, 'Votre demande a bien été enregistrée, et le covoitureur en a été averti.')
			else :
				messages.success('Vous êtes désormais un passager de ce covoiturage.')
		else :
			messages.error("Vous n'êtes pas autorisé à faire cela.")
	return redirect('rideshare_ride_detail', pk=ride.pk)



@login_required
def DeleteRider(request, pk):
	rider = get_object_or_404(Rider, pk=pk)
	ride = rider.ride
	if ride.owner == request.user :
#		if form.get('message') :
#			explanation = '%0ASon message à votre attention:%0A<blockquote><i>{}</i></blockquote>'.format(form.get('message'))
#		explanation = ''
#		TODO : add support for explaining why rider was kicked out
		send_mail(
			subject='Votre demande de covoiturage a été annulée !',
			message='''
				{greeting} votre covoiturage {ride_url} a été annulé par {ride_owner}. Vous pouvez réaliser une nouvelle demande de covoiturage. {signature}
				'''.format(
					greeting=email_greeting(request),
					ride_url= request.build_absolute_uri(reverse('rideshare_ride_detail', args=[ride.pk,])),
					ride_owner=ride.owner.get_full_name(),
					signature=email_signature(request),
					), # TODO : also trigger this on ride cancellation
			html_message='''
				<p>{greeting},</p>
				<p>Votre covoiturage {ride_url} a été annulé par {ride_owner}. Vous pouvez réaliser une nouvelle demande de covoiturage.</p>
				<p>{signature}</p>
				'''.format(
					greeting=email_greeting(request),
					ride_url= request.build_absolute_uri(reverse('rideshare_ride_detail', args=[ride.pk,])),
					ride_owner=ride.owner.get_full_name(),

rideshare/templates/rideshare/ride_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}{{ block.super }}

<div class="
	col-xl-6 offset-xl-3
	col-lg-8 offset-lg-2
	col-md-10 offset-md-1
	col-sm-12
	" style="margin-top: 2em">

<!-- HEADER -->

<div style="text-align: left;">

	<a class="btn btn-secondary" href="{% url 'rideshare_ride_list' ride.event.slug %}">
		<i class="fa fa-arrow-left"></i> Retour à la liste
		</a> 
	
</div>

<hr/>
<!-- CONTENT -->

<div style="text-align: left;">
	<h1 class="page-title">Détail du trajet</h1>
	<p><strong>Prix par participant :</strong> {{ object.price }} €</p>
	<p><strong>Places disponibles :</strong>
		<span class="remaining-seats"
			data-rider-count="{{ object.rider_set.all.count }}"
			data-seats="{{object.seats}}"></span> / {{ object.seats }}
	</p>
	<p><strong>Géré par :</strong>
		{% if object.owner == user %}moi
		{% else %}{{ object.owner.first_name }} {{ object.owner.last_name }}
		{% endif %}
	</p>
	<p><strong>Tel :</strong> {{ ride.phone }}</p>	
	{% if ride.message %}
	<p><strong>Message du covoitureur :</strong><br/>
		<em>{{ ride.message }}</em>
	</p>
	{% elif user == ride.owner %}
	<p class="text-muted"><em>Vous n'avez pas écrit de message à l'attention des participants. Cliquez sur "Modifier" pour en ajouter un !</em></p>
	{% endif %}
	
	{% if user == ride.owner or user.is_staff %}
	<p>
		{% if user == ride.owner %}
		<a class="btn btn-secondary" href="{% url 'rideshare_ride_update' object.pk %}"><i class="fa fa-cog"></i> Modifier</a>
		{% endif %}
		{% if user.is_staff %}
		<a class="btn btn-secondary" href="/arriere-boutique/rideshare/ride/{{ object.pk }}"><i class="fa fa-wrench"></i> Administrer</a>
		{% endif %}
	</p>
	{% endif %}	
</div>

<hr/>

{% if user not in users_who_are_riders and user != object.owner %}
<div class="ride__interactions">
	<a class="ride__join btn btn-primary btn-block" href="{% url 'rideshare_join_ride' object.pk %}">
		<i class="fa fa-arrow-circle-right"></i>&nbsp;
		{% if object.rider_set.all.count >= object.seats %}Je m'ajoute à la liste d'attente
		{% else %}Je souhaite participer à ce trajet
		{% endif %}
	</a>
</div>
{% endif %}

<br/>

<!-- {% if user in object.riders.all %}"true"{% else %}"false"{% endif %} -->

<div class="ride__stops">
{% for stop in object.stop_set.all %}
	<div class="ride__stop">
		<div class="card card-block">
			<div class="ride__stop__locality">{{ stop.location.locality }}</div>
			{% if stop.location.locality != stop.location.name %}
			<div class="ride__stop__name text-muted">{{ stop.location.name }}</div>
			{% endif %}
			<div class="ride__stop__datetime">{{ stop.time|date:"l d F" }} à {{ stop.time|time:"H:i" }}</div>
		</div>
	</div>
{% endfor %}
</div>

{% if object.rider_set.all %}
<hr/>
<div>
	<h4 style="text-align: left;">Participants :</h4>
	
	{% for rider in object.rider_set.all %}
		<div class="rider card card-inverse
			{% if not rider.accepted %} card-warning
			{% else %} card-primary{% endif %}">
			<div class="card-block card-text">
				<div class="rider__name">
					{% if rider.user %}{{ rider.user.first_name }} {{ rider.user.last_name }}
					{% else %}{{ rider.name }}{% endif %}
				</div>
				{% if user == ride.owner %}
				<div class="rider__email">{{ rider.email }}</div>
				<div class="rider__phone">{{ rider.phone }}</div>
				{% if rider.message %}
					</div>
					<div class="card-footer card-text">
					<div class="rider__message">{{ rider.message }}</div>
				{% endif %}
				{% elif not rider.accepted %}
					<div>En attente de confirmation</div>
				{% endif %}
			</div>
			{% if rider.accepted and user == ride.owner %}
			<div class="card-footer" style="text-align: right;">
				<small class="rider__edit">
					<a class="card-text" href="{% url 'rideshare_rider_delete' rider.pk %}">
						<i class="fa fa-trash-o"></i> Supprimer ce participant
					</a>
				</small>
			</div>
			{% elif user == ride.owner %}
			<div class="card-footer">
				{% if user == ride.owner %}
				<div class="card-text">
					<a class="btn btn-success btn-sm" href="{% url 'rideshare_rider_accept' rider.pk %}">
					<i class="fa fa-check"></i> Accepter
					</a>
					&nbsp;
					<a class="btn btn-danger btn-sm" href="{% url 'rideshare_rider_deny' rider.pk %}">
					<i class="fa fa-times"></i> Refuser
					</a>
				</div>
				{% endif%}
			</div>
			{% endif %}
		</div>
	{% endfor %}
</div>
{% endif %}

</div>

<style>

body { text-align: center; margin-bottom: 2em; }

.ride__stop > span { display: table-cell; padding: 0 1em; }

.ride__stop:not(:first-child):before { content: '\f063'; font-family: FontAwesome; font-size: 2em; position: relative; top: -.15em; }

.ride__price { font-size: 1.6em; margin-bottom: .25em; }

.ride__stop__locality { font-size: 1.8em; }
.ride__stop__name { font-style: italic; }

.rider { text-align: left; }
.rider__name { display: block; text-transform: uppercase; font-size: 1.35rem; color: white; }
.rider__email:before { content: '\f0e0'; font-family: "FontAwesome"; margin-right: .5em; }
.rider__phone:before { content: '\f095'; font-family: "FontAwesome"; margin-right: .5em; }
.rider__message

.card-warning .rider__edit { display: none; }

</style>

{% endblock content %}



{% block scripts %} {{ block.super }}

<script>

$( document ).ready(function() {
		
	window.rideshareStore = {
	//	'regions': [],
	}

	function $call(url) {
		return $.ajax({url: url})
	}

	$('.remaining-seats').each(function(){
		var remainingSeats = $(this).data('seats') - $(this).data('rider-count')
		if (remainingSeats == 0) remainingSeats = "Complet"
		$(this).text(remainingSeats)
	})

})

</script>

{% endblock scripts %}

rideshare/templates/rideshare/ride_join_form.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}{{ block.super }}

<div class="
	col-xl-6 offset-xl-3
	col-lg-8 offset-lg-2
	col-md-10 offset-md-1
	col-sm-12
	" style="margin-top: 2em">

<!-- HEADER -->

<h1 class="page-title">Demander à rejoindre un trajet en covoiturage</h1>

<br/>

<!-- CONTENT -->
<form method="post" action="{% url 'rideshare_rider_create' %}" style="text-align: left;">
	{% csrf_token %}
	<input type="hidden" name="ride_pk" value="{{ ride_pk }}" required />
	<input type="hidden" name="user_pk" value="{{ user_pk }}" required />
	{% if not user.is_authenticated %}
	<div class="form-group row">
		<label class="col-xs-4 col-form-label">Prénom et Nom</label>
		<div class="col-xs-8">
			<input class="form-control" type="text" name="name" required />
		</div>
	</div>
	<div class="form-group row">
		<label class="col-xs-4 col-form-label">Email</label>
		<div class="col-xs-8">
			<input class="form-control" type="email" name="email" required />
		</div>
	</div>
	{% endif %}
	<div class="form-group row">
		<label class="col-xs-4 col-form-label">Téléphone</label>
		<div class="col-xs-8">
			<input class="form-control" type="text" name="phone" required
			placeholder="00 00 00 00 00"/>
		</div>
	</div>
	<div class="form-group row">
		<label class="col-xs-4 col-form-label">Message</label>
		<div class="col-xs-8">
			<textarea class="form-control" type="text" name="message" maxlength="1000"
			placeholder="Un message addressé à l'organisateur de ce covoiturage..."></textarea>
		</div>
	</div>
	<button type="submit" class="ride__join btn btn-primary btn-block">
		<i class="fa fa-arrow-circle-right"></i>&nbsp;
		Demander à rejoindre
	</button>
</form>

</div>

<style>

body { margin-bottom: 2em; }

</style>

{% endblock content %}



{% block scripts %} {{ block.super }}

<script>

$( document ).ready(function() {
	//
})

</script>

{% endblock scripts %}